name = "aoc_24"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gladvent = ">= 2.0.2 and < 3.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"

[gladvent.2024.1]
pt_1 = 2192892
pt_2 = 22962826
